# -*- coding: utf-8 -*-
"""Primeornot

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bzU7mDXB_ZMWfaUFSs4QeNxRfjq6frrf
"""

def primeornot(num,flag):
  if num > 1:
    for i in range(2, num):
        if (num % i) == 0:
            flag = True
            break
  if flag:
    print(num, "is not a prime number")
  else:
    print(num, "is a prime number")

num = int(input("Enter a number: "))
flag = False
primeornot(num,flag)