# -*- coding: utf-8 -*-
"""WheatherReportUsingOWM

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YgWPpPHCE3FOvCR3te_upBmEl0oD1mhy
"""

import requests, json
BASE_URL = "https://api.openweathermap.org/data/2.5/weather?"
CITY = input()
API_KEY = "b6fae34e9a98c917999a7c03172c208f"
URL = BASE_URL + "q=" + CITY + "&appid=" + API_KEY
response = requests.get(URL)
if response.status_code == 200:
   data = response.json()
   main = data['main']
   temperature = main['temp']
   report = data['weather']
   print(f"{CITY:}")
   print(f"Temperature: {temperature-273}")
   print(f"Weather Report: {report[0]['description']}")
else:
   print("Error in the HTTP request")