# -*- coding: utf-8 -*-
"""YoutubeDownloader

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14kMK_oDxTtAtwZqPnjZ77ihtSZ0vfBzB
"""

!pip install pytube

from pytube import YouTube

link=input()
url =YouTube(str(link))
video = url.streams.first()
video.download()